# Generated by Django 5.0.8 on 2024-08-27 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0018_admininfo_channels_channelsponsor_checker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=5808959400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 27, 18, 16, 22, 763511, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
