# Generated by Django 5.0.8 on 2024-08-31 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0022_alter_user_uid_alter_usertg_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=5769418072, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 31, 10, 11, 44, 974299, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
