# Generated by Django 5.0.8 on 2024-09-04 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0024_alter_user_uid_alter_usertg_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=1733315298, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 4, 16, 33, 52, 986081, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
